name: Windows python build
run-name: ${{ github.actor }} Windows python build
on: 
  workflow_dispatch: 
  pull_request: 
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: read

jobs: 
  windows_python_build:
    runs-on: windows-latest 
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
      - name: Check cmake
        run: cmake --version
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            python
      - name: Configure
        run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DBUILD_PYTHON=ON
      - name: Build
        run: cmake --build build
